# Generated by Django 3.2.4 on 2022-05-06 09:30

from django.db import migrations, models
import ks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ks_pnuh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.PositiveIntegerField(blank=True, help_text='대상자 번호', null=True, verbose_name='대상자 번호')),
                ('icf_date', models.DateField(blank=True, help_text='연구 동의 날짜', null=True, verbose_name='연구 동의 날짜')),
                ('sex', models.IntegerField(blank=True, choices=[(1, '남자'), (2, '여자')], help_text='성별', null=True, verbose_name='성별')),
                ('birthdate', models.DateField(blank=True, help_text='생년월일', null=True, verbose_name='생년월일')),
                ('diagnosis_age', models.DateField(blank=True, help_text='가부키 증후군 진단 받은 날짜', null=True, verbose_name='진단 받은 날짜')),
                ('familyhistory_1', models.IntegerField(blank=True, choices=[(1, '있음'), (2, '없음'), (3, '모름')], help_text='가족 병력<br/>', null=True, verbose_name='가족 병력')),
                ('familyhistory_2', models.IntegerField(blank=True, choices=[(1, '부'), (2, '모'), (3, '형제'), (4, '자녀')], help_text='가족 병력 관계<br/>', null=True, verbose_name='가족 병력 관계')),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, help_text='출생시 체중', max_digits=10, null=True, verbose_name='출생시 체중')),
                ('gestational_age', models.TextField(blank=True, help_text='출생시 재태주수', null=True, verbose_name='출생시 재태주수')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='현재 키', max_digits=10, null=True, verbose_name='현재 키')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='현재 체중', max_digits=10, null=True, verbose_name='현재 체중')),
                ('disability_grade_1', models.IntegerField(blank=True, choices=[(1, '1급'), (2, '2급'), (3, '3급'), (4, '4급'), (5, '5급'), (6, '6급'), (7, '등급 외(장애 정도)')], help_text='지적장애 등급', null=True, verbose_name='지적장애 등급')),
                ('disability_grade_2', models.IntegerField(blank=True, choices=[(1, '장애 정도가 심한 장애인(중증)'), (2, '장애 정도가 심하지 않은 장애인(경증)'), (3, '장애 정도 미해당')], help_text='지적장애 정도', null=True, verbose_name='지적장애 정도')),
                ('growth', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], help_text='성장 이상 소견<br/>', null=True, verbose_name='성장 이상 소견')),
                ('growth_hormone_1', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='성장호르몬결핍증 유무', null=True, verbose_name='성장호르몬결핍증 유무')),
                ('growth_hormone_2', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='성장 호르몬(IGF-1)검사 시행', null=True, verbose_name='성장 호르몬(IGF-1)검사 시행')),
                ('growth_hormone_3', models.DecimalField(blank=True, decimal_places=2, help_text='가장 최근 성장호르몬 수치', max_digits=10, null=True, verbose_name='성장호르몬(IGF-1)수치')),
                ('precocious_puberty', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='성조숙증진단', null=True, verbose_name='성조숙증진단')),
                ('ear', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, 'N'), (1, 'Sensorineural hearing impairmen'), (2, 'Conductive hearing impairment'), (3, 'Macrotia'), (4, 'Protruding ear')], max_length=200, null=True), blank=True, help_text='귀 관련 이상 소견', null=True, size=None, verbose_name='귀 관련 이상 소견')),
                ('ear_test', models.TextField(blank=True, help_text='귀 관련 검사 소견', null=True, verbose_name='귀 관련 검사 소견')),
                ('eye', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, 'N'), (1, 'Nystagmus'), (2, 'Strabismus'), (3, 'Microcornea'), (4, 'Ptosis'), (5, 'Blue sclerae'), (6, 'Coloboma')], max_length=200, null=True), blank=True, help_text='안과적 이상 소견', null=True, size=None, verbose_name='안과적 이상 소견')),
                ('eye_test', models.TextField(blank=True, help_text='안과적 검사 소견', null=True, verbose_name='안과적 검사 소견')),
                ('head_and_neck', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, 'N'), (1, 'Abnormality of the dentition'), (2, 'Cleft palate'), (3, 'Eversion of lateral third of lower eyelids'), (4, 'Short columella'), (5, 'Microdontia'), (6, 'Widely spaced teeth'), (7, 'Hypodontia'), (8, 'Mask-like facies'), (9, 'High palate'), (10, 'Oral cleft'), (11, 'Abnormality of dental morphology')], max_length=200, null=True), blank=True, help_text='머리와 목 이상 소견', null=True, size=None, verbose_name='머리와 목 이상 소견')),
                ('head_and_neck_test', models.TextField(blank=True, help_text='머리와 목 검사 소견', null=True, verbose_name='머리와 목 검사 소견')),
                ('cardiovascular', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(1, 'N'), (2, 'Abnormal cardiac septum morphology'), (3, 'Coarctation of aorta')], max_length=200, null=True), blank=True, help_text='심혈관 이상 소견', null=True, size=None, verbose_name='심혈관 이상 소견')),
                ('cardiovascular_test', models.TextField(blank=True, help_text='심혈관 검사 소견', null=True, verbose_name='심혈관 검사 소견')),
                ('digestive_system', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='소화계 이상 소견', null=True, verbose_name='소화계 이상 소견')),
                ('digestive_system_test', models.TextField(blank=True, help_text='소화계 검사 소견', null=True, verbose_name='소화계 검사 소견')),
                ('genitourinary_system', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '"N'), (1, 'Hypoplasia of penis'), (2, 'Renal hypoplasia /aplasia'), (3, 'Duplicated collecting system'), (4, 'Ureteropelvic junction obstruction'), (5, 'Hypospadias'), (6, 'Cryptorchidism'), (7, 'Hydronephrosis'), (8, 'Abnormal localization of kidney'), (9, 'Crossed fused renal ectopia')], max_length=200, null=True), blank=True, help_text='비뇨 생식기 이상 소견', null=True, size=None, verbose_name='비뇨 생식기 이상 유무')),
                ('genitourinary_system_test', models.TextField(blank=True, help_text='비뇨 생식기 검사 소견', null=True, verbose_name='비뇨 생식기 이상 관련 검사 소견')),
                ('Immunology', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '"N'), (1, 'Abnormality of immune system physiology'), (2, 'Recurrent infections')], max_length=200, null=True), blank=True, help_text='면역학 이상 소견', null=True, size=None, verbose_name='면역학 이상 유무')),
                ('thyroid', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='갑상선기능이상', null=True, verbose_name='갑상선기능이상')),
                ('thyroid_test', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='갑상선기능 검사 시행', null=True, verbose_name='갑상선기능 검사 시행')),
                ('tsh', models.DecimalField(blank=True, decimal_places=2, help_text='가장 최근 TSH 수치', max_digits=10, null=True, verbose_name='TSH')),
                ('t3', models.DecimalField(blank=True, decimal_places=2, help_text='가장 최근 T3 수치', max_digits=10, null=True, verbose_name='T3')),
                ('free_t4', models.DecimalField(blank=True, decimal_places=2, help_text='가장 최근 free T4 수치', max_digits=10, null=True, verbose_name='free T4')),
                ('skeletal_system', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, 'N'), (1, 'Scoliosis'), (2, 'Abnormal form of the vertebral bodies'), (3, 'Butterfly vertebrae'), (4, 'Vertebral clefting'), (5, 'Joint hyperflexibility'), (6, 'Hemiverteb')], max_length=200, null=True), blank=True, help_text='골격계 이상 소견', null=True, size=None, verbose_name='골격계 이상 소견')),
                ('skeletal_system_test', models.TextField(blank=True, help_text='골격계 검사 소견', null=True, verbose_name='골격계 검사 소견')),
                ('hypotonia', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='근기능 저하 유무', null=True, verbose_name='근기능 저하 유무')),
                ('limbs', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, 'N'), (1, 'Small hand'), (2, 'Short 5th finger'), (4, 'Short middle phalanx of finger'), (5, 'Hip dislocation')], max_length=200, null=True), blank=True, help_text='사지 이상 소견', null=True, size=None, verbose_name='사지 이상 소견')),
                ('limbs_test', models.TextField(blank=True, help_text='사지 검사 소견', null=True, verbose_name='사지 검사 소견')),
                ('congenital_diaphragmatic_hernia', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='선천성 횡경막 탈장 유무', null=True, verbose_name='선천성 횡경막 탈장 유무')),
                ('skin_hair_nails', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, 'N'), (1, 'Highly arched eyebrow'), (2, 'Abnormal dermatoglyphics'), (3, 'Lip pit'), (4, 'Preauricular skin tag'), (5, 'Sparse lateral eyebrow'), (6, 'Long eyelashes')], max_length=200, null=True), blank=True, help_text='피부, 머리카락, 손톱 이상 소견', null=True, size=None, verbose_name='피부, 머리카락, 손톱 이상 소견')),
                ('skin_hair_nails_test', models.TextField(blank=True, help_text='피부, 머리카락, 손톱 검사 소견', null=True, verbose_name='피부, 머리카락, 손톱 검사 소견')),
                ('nervous_system', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, 'N'), (1, 'Seizure'), (2, 'Cerebral cortical atrophy'), (3, 'Ventriculomegaly'), (4, 'EEG abnormality'), (5, 'Hydrocephalus'), (6, 'Microcephaly')], max_length=200, null=True), blank=True, help_text='신경계 이상 유무', null=True, size=None, verbose_name='신경계 이상 소견')),
                ('nervous_system_test', models.TextField(blank=True, help_text='신경계 검사 유무', null=True, verbose_name='신경계 검사 소견')),
                ('adhd', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='ADHD 유무', null=True, verbose_name='ADHD 유무')),
                ('autism', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='자폐증 유무', null=True, verbose_name='자폐증 유무')),
                ('diabetes', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='당뇨병 유무', null=True, verbose_name='당뇨병 유무')),
                ('hba1c', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='HbA1C 검사 시행', null=True, verbose_name='HbA1C 검사 시행 ')),
                ('hba1c_test', models.DecimalField(blank=True, decimal_places=2, help_text='가장 최근 HbA1C 수치', max_digits=10, null=True, verbose_name='HbA1C 수치')),
                ('tumor_1', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='종양 유무', null=True, verbose_name='종양 유무')),
                ('tumor_2', ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(1, '혈액암'), (2, '고형암')], max_length=200, null=True), blank=True, help_text='혈액암 혹은 고형암 진단', null=True, size=None, verbose_name='혈액암 혹은 고형암 진단')),
                ('tumor_test', models.TextField(blank=True, help_text='종양 관련 검사 소견', null=True, verbose_name='종양 관련 검사 소견')),
                ('genetic_test', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], help_text='유전자 검사 시행 여부', null=True, verbose_name='유전자 검사 시행 여부')),
                ('mll2', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], help_text='MLL2 유전자 변이 여부', null=True, verbose_name='MLL2 유전자 변이 여부')),
                ('dna', models.CharField(blank=True, help_text='유전자 변이 (DNA)', max_length=444, null=True, verbose_name='유전자 변이 (DNA)')),
                ('protein', models.CharField(blank=True, help_text='유전자 변이 (Protein)', max_length=444, null=True, verbose_name='유전자 변이 (Protein)')),
                ('domain', models.TextField(blank=True, help_text='Domain', null=True, verbose_name='Domain')),
                ('mutation_type', models.TextField(blank=True, help_text='Mutation type', null=True, verbose_name='Mutation type')),
                ('Inframe_deletion_or_insertion', models.TextField(blank=True, help_text='Inframe deletion or insertion', null=True, verbose_name='Inframe deletion or insertion')),
                ('haploinsufficiency_type', models.TextField(blank=True, help_text='haploinsufficiency type', null=True, verbose_name='haploinsufficiency type')),
                ('novel_mutation', models.TextField(blank=True, help_text='Novel mutation', null=True, verbose_name='Novel mutation')),
                ('brain_mr', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='뇌 MR 시행 유무', null=True, verbose_name='뇌 MR 시행 유무')),
                ('brain_mr_test', models.TextField(blank=True, help_text='뇌 MR 검사 소견', null=True, verbose_name='뇌 MR 검사 소견')),
                ('operation_1', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='수술 유무', null=True, verbose_name='수술 유무')),
                ('operation_2', models.PositiveIntegerField(blank=True, help_text='수술 횟수', null=True, verbose_name='수술 횟수')),
                ('operation_3', models.TextField(blank=True, help_text='수술 종류', null=True, verbose_name='수술 종류')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
