# Generated by Django 3.2.4 on 2022-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks', '0002_ks_amc_ks_cbnuh_ks_knuh_ks_smc_ks_snuh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ks_amc',
            options={'verbose_name': '가부키증후군_서울아산병원', 'verbose_name_plural': '가부키증후군_서울아산병원'},
        ),
        migrations.AlterModelOptions(
            name='ks_cbnuh',
            options={'verbose_name': '가부키증후군_충북대병원', 'verbose_name_plural': '가부키증후군_충북대병원'},
        ),
        migrations.AlterModelOptions(
            name='ks_knuh',
            options={'verbose_name': '가부키증후군_칠곡경북대병원', 'verbose_name_plural': '가부키증후군_칠곡경북대병원'},
        ),
        migrations.AlterModelOptions(
            name='ks_pnuh',
            options={'verbose_name': '가부키증후군_양산부산대병원', 'verbose_name_plural': '가부키증후군_양산부산대병원'},
        ),
        migrations.AlterModelOptions(
            name='ks_smc',
            options={'verbose_name': '가부키증후군_삼성서울병원', 'verbose_name_plural': '가부키증후군_삼성서울병원'},
        ),
        migrations.AlterModelOptions(
            name='ks_snuh',
            options={'verbose_name': '가부키증후군_서울대학교병원', 'verbose_name_plural': '가부키증후군_서울대학교병원'},
        ),
    ]
