# Generated by Django 3.2.4 on 2022-07-20 07:00

from django.db import migrations, models
import ks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ks', '0004_auto_20220711_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='ks_pnuh',
            name='familyhistory_1_multiple',
            field=ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(1, '있음'), (2, '없음'), (3, '모름')], max_length=200, null=True), blank=True, help_text='가족 병력<br/>', null=True, size=None, verbose_name='가족 병력'),
        ),
        migrations.AddField(
            model_name='ks_snuh',
            name='familyhistory_1_multiple',
            field=ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(1, '있음'), (2, '없음'), (3, '모름')], max_length=200, null=True), blank=True, help_text='가족 병력<br/>', null=True, size=None, verbose_name='가족 병력'),
        ),
        migrations.AlterField(
            model_name='ks_pnuh',
            name='tumor_2',
            field=ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '미해당'), (1, '혈액암'), (2, '고형암')], max_length=200, null=True), blank=True, help_text='혈액암 혹은 고형암 진단', null=True, size=None, verbose_name='혈액암 혹은 고형암 진단'),
        ),
        migrations.AlterField(
            model_name='ks_snuh',
            name='tumor_2',
            field=ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '미해당'), (1, '혈액암'), (2, '고형암')], max_length=200, null=True), blank=True, help_text='혈액암 혹은 고형암 진단', null=True, size=None, verbose_name='혈액암 혹은 고형암 진단'),
        ),
    ]
