# Generated by Django 3.2.4 on 2022-07-21 06:00

from django.db import migrations, models
import ks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ks', '0005_auto_20220720_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ks_pnuh',
            name='familyhistory_1_multiple',
        ),
        migrations.RemoveField(
            model_name='ks_snuh',
            name='familyhistory_1_multiple',
        ),
        migrations.AddField(
            model_name='ks_pnuh',
            name='familyhistory_2_multiple',
            field=ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '-'), (1, '부'), (2, '모'), (3, '형제'), (4, '자녀')], max_length=200, null=True), blank=True, help_text='가족 병력 관계<br/>', null=True, size=None, verbose_name='가족 병력 관계'),
        ),
        migrations.AddField(
            model_name='ks_snuh',
            name='familyhistory_2_multiple',
            field=ks.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '-'), (1, '부'), (2, '모'), (3, '형제'), (4, '자녀')], max_length=200, null=True), blank=True, help_text='가족 병력 관계<br/>', null=True, size=None, verbose_name='가족 병력 관계'),
        ),
        migrations.AlterField(
            model_name='ks_pnuh',
            name='familyhistory_2',
            field=models.IntegerField(blank=True, choices=[(0, '-'), (1, '부'), (2, '모'), (3, '형제'), (4, '자녀')], help_text='가족 병력 관계<br/>', null=True, verbose_name='가족 병력 관계'),
        ),
        migrations.AlterField(
            model_name='ks_snuh',
            name='familyhistory_2',
            field=models.IntegerField(blank=True, choices=[(0, '-'), (1, '부'), (2, '모'), (3, '형제'), (4, '자녀')], help_text='가족 병력 관계<br/>', null=True, verbose_name='가족 병력 관계'),
        ),
    ]
