# Generated by Django 3.2.4 on 2022-07-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ks', '0006_auto_20220721_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ks_pnuh',
            name='familyhistory_2',
        ),
        migrations.RemoveField(
            model_name='ks_snuh',
            name='familyhistory_2',
        ),
    ]
