# Generated by Django 3.2.4 on 2022-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks', '0008_auto_20220905_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='ks_pnuh',
            name='initials',
            field=models.CharField(blank=True, help_text='이니셜', max_length=444, null=True, verbose_name='이니셜'),
        ),
    ]
