# Generated by Django 3.2.4 on 2022-09-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks', '0009_ks_pnuh_initials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ks_pnuh_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_1', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='과거 병력 여부', null=True, verbose_name='과거 병력 여부')),
                ('history_2', models.TextField(blank=True, help_text='과거 병력 질환명', null=True, verbose_name='과거 병력 질환명')),
                ('ks_pnuh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks_pnuh_history', to='ks.ks_pnuh')),
            ],
        ),
        migrations.CreateModel(
            name='Ks_pnuh_con_med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_med_1', models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오')], help_text='병용약물 유무', null=True, verbose_name='병용약물 유무')),
                ('con_med_2', models.TextField(blank=True, help_text='약물명', null=True, verbose_name='약물명')),
                ('ks_pnuh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ks_pnuh_con_med', to='ks.ks_pnuh')),
            ],
        ),
    ]
