# Generated by Django 3.2.4 on 2021-08-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='차트번호')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='성명')),
                ('birth_year_and_month', models.DateTimeField(blank=True, verbose_name='생년월일')),
                ('sex', models.PositiveIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'All')], null=True, verbose_name='SEX')),
                ('finding', models.TextField(blank=True, verbose_name='특이사항')),
                ('sortation', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='구분')),
                ('ARK_SPH', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_SPH')),
                ('ARK_CYL', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_CYL')),
                ('ARK_AXIS', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_AXIS')),
                ('ARK_K1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_K1')),
                ('ARK_K2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_K2')),
                ('ARK_KM', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_KM')),
                ('ARK_K_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_K(cyl)')),
                ('ARK_K_Axis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARK_K(Axis)')),
                ('UDVA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='UDVA')),
                ('UNVA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='UNVA')),
                ('CDVA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CDVA')),
                ('CNVA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CNVA')),
                ('IOP', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IOP')),
                ('OCT_CST', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='OCT_CST')),
                ('Cones_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cones_a')),
                ('Cones_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cones_b')),
                ('Flicker', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flicker')),
                ('Pattern_N35_mono', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pattern_N35(단안)')),
                ('Pattern_P50_mono', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pattern_P50(단안)')),
                ('Pattern_N95_mono', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pattern_N95(단안)')),
                ('Pattern_N35_bi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pattern_N35(양안)')),
                ('Pattern_P50_bi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pattern_P50(양안)')),
                ('Pattern_N95_bi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pattern_N95(양안)')),
                ('Rods_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rods_a')),
                ('Rods_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rods_b')),
                ('Maximal_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximal_a')),
                ('Maximal_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximal_b')),
                ('Maximal_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximal_c')),
                ('VEP_N75', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VEP_N75')),
                ('VEP_P100', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VEP_P100')),
                ('VEP_N145', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VEP_N145')),
                ('VEP_P1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VEP_P1')),
                ('VEP_P2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VEP_P2')),
            ],
        ),
    ]
