# Generated by Django 3.2.4 on 2021-08-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ird',
            name='birth_year_and_month',
            field=models.DateTimeField(blank=True, verbose_name='생년월일'),
        ),
    ]
