# Generated by Django 3.2.4 on 2021-12-10 03:08

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0002_irdhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ird',
            name='birth_year_and_month',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='birthdate',
        ),
        migrations.AlterField(
            model_name='ird',
            name='name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='성명'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='address',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, help_text='도/시', null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='성명', max_length=20, null=True, verbose_name='이름'),
        ),
    ]
