# Generated by Django 3.2.4 on 2021-12-10 03:20

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0003_auto_20211210_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ird',
            name='birth_year_and_month',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='birthdate',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, help_text='생년월일', null=True, verbose_name='생년월일'),
        ),
    ]
