# Generated by Django 3.2.4 on 2021-12-16 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0004_auto_20211210_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='irdhistory',
            name='mutation_list',
            field=models.FileField(blank=True, null=True, upload_to='ird/mutation/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='IRD 관련 유젼자 변이'),
        ),
    ]
