# Generated by Django 3.2.4 on 2022-04-21 03:32

from django.db import migrations, models
import ird.models


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0005_alter_irdhistory_best_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irdhistory',
            name='cataract_op',
            field=ird.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(1, '오른쪽 눈'), (2, '왼쪽 눈'), (3, '수술하지 않음')], max_length=200, null=True), blank=True, help_text='백내장 수술을 받은 적이 있나요?', null=True, size=None, verbose_name='백내장 수술'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='first_symptom_age',
            field=models.TextField(blank=True, help_text='처음 눈에 증상이 나타난 나이는 언제인가요?', null=True, verbose_name='첫 증상 나이'),
        ),
    ]
