# Generated by Django 3.1.8 on 2022-01-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0005_irdhistory_mutation_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irdhistory',
            name='cdva',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='cnva',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='cones_a',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='cones_b',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='cst',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='cyl',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='flicker',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='iop',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='k_axis',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='k_cyl',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='km',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='maximal_a',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='maximal_b',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='maximal_c',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='od_os',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='pattern_n35_bi',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='pattern_n35_mono',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='pattern_n95_bi',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='pattern_n95_mono',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='pattern_p50_bi',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='pattern_p50_mono',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='rods_a',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='rods_b',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='sph',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='udva',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='unva',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='vfi',
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='case_history',
            field=models.ImageField(blank=True, help_text='실퇴본에서 조사한 병력 청취 기록입니다.', null=True, upload_to='ird/history/%Y/%m/%d', verbose_name='실퇴본_병력청취'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cdva_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='원거리교정시력', max_digits=10, null=True, verbose_name='CDVA OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cdva_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='원거리교정시력', max_digits=10, null=True, verbose_name='CDVA OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cnva_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='근거리교정시력', max_digits=10, null=True, verbose_name='CNVA OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cnva_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='근거리교정시력', max_digits=10, null=True, verbose_name='CNVA OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cones_a_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Cones_a OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cones_a_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Cones_a OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cones_b_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Cones_b OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cones_b_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Cones_b OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cst_od',
            field=models.PositiveIntegerField(blank=True, help_text='중심망막 두께', null=True, verbose_name='HOCT_CST OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cst_os',
            field=models.PositiveIntegerField(blank=True, help_text='중심망막 두께', null=True, verbose_name='HOCT_CST OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cyl_od',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='난시', max_digits=10, null=True, verbose_name='ARK_CYL OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cyl_os',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='난시', max_digits=10, null=True, verbose_name='ARK_CYL OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cystoid_macular_edema_od',
            field=models.IntegerField(blank=True, choices=[(0, '없음'), (1, '있음')], help_text='황반 부음', null=True, verbose_name='CME OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cystoid_macular_edema_os',
            field=models.IntegerField(blank=True, choices=[(0, '없음'), (1, '있음')], help_text='황반 부음', null=True, verbose_name='CME OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='flicker_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Flicker OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='flicker_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Flicker OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='iop_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='안압', max_digits=10, null=True, verbose_name='IOP OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='iop_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='안압', max_digits=10, null=True, verbose_name='IOP OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='job',
            field=models.CharField(blank=True, help_text='어떤 일을 하고 계신가요?', max_length=255, null=True, verbose_name='직업'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='k_axis_od',
            field=models.PositiveIntegerField(blank=True, help_text='각막난시축', null=True, verbose_name='ARK_K(Axis) OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='k_axis_os',
            field=models.PositiveIntegerField(blank=True, help_text='각막난시축', null=True, verbose_name='ARK_K(Axis) OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='k_cyl_od',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='각막난시량', max_digits=10, null=True, verbose_name='ARK_K(Cyl) OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='k_cyl_os',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='각막난시량', max_digits=10, null=True, verbose_name='ARK_K(Cyl) OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='km_od',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='각막난시', max_digits=10, null=True, verbose_name='ARK_KM OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='km_os',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='각막난시', max_digits=10, null=True, verbose_name='ARK_KM OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='maximal_a_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Maximal_a OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='maximal_a_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Maximal_a OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='maximal_b_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Maximal_b OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='maximal_b_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Maximal_b OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='maximal_c_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Maximal_c OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='maximal_c_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Maximal_c OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n35_bi_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n35_bi OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n35_bi_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n35_bi OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n35_mono_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n35_mono OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n35_mono_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n35_mono OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n95_bi_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n95_bi OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n95_bi_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n95_bi OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n95_mono_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n95_mono OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_n95_mono_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_n95_mono OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_p50_bi_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_p50_bi OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_p50_bi_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_p50_bi OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_p50_mono_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_p50_mono OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='pattern_p50_mono_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Pattern_p50_mono OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='retinitis_punctata_albescens_od',
            field=models.IntegerField(blank=True, choices=[(0, '없음'), (1, '있음')], help_text='백점상망막염', null=True, verbose_name='retinitis_punctata_albescens OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='retinitis_punctata_albescens_os',
            field=models.IntegerField(blank=True, choices=[(0, '없음'), (1, '있음')], help_text='백점상망막염', null=True, verbose_name='retinitis_punctata_albescens OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='rods_a_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Rods_a OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='rods_a_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Rods_a OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='rods_b_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Rods_b OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='rods_b_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='망막전위도검사', max_digits=10, null=True, verbose_name='ERG_Rods_b OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='sector_rp_od',
            field=models.IntegerField(blank=True, choices=[(0, '없음'), (1, '있음')], help_text='부채형 RP', null=True, verbose_name='sector_RP OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='sector_rp_os',
            field=models.IntegerField(blank=True, choices=[(0, '없음'), (1, '있음')], help_text='부채형 RP', null=True, verbose_name='sector_RP OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='sph_od',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='원/근시', max_digits=10, null=True, verbose_name='ARK_SPH OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='sph_os',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='원/근시', max_digits=10, null=True, verbose_name='ARK_SPH OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='udva_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='원거리나안시력', max_digits=10, null=True, verbose_name='UDVA OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='udva_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='원거리나안시력', max_digits=10, null=True, verbose_name='UDVA OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='unva_od',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='근거리나안시력', max_digits=10, null=True, verbose_name='UNVA OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='unva_os',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='근거리나안시력', max_digits=10, null=True, verbose_name='UNVA OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='vfi_od_full',
            field=models.PositiveIntegerField(blank=True, help_text='중심시야 대비감도 전체', null=True, verbose_name='VF_VFI_full OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='vfi_od_part',
            field=models.PositiveIntegerField(blank=True, help_text='중심시야 대비감도 부분', null=True, verbose_name='VF_VFI_part OD'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='vfi_os_full',
            field=models.PositiveIntegerField(blank=True, help_text='중심시야 대비감도 전체', null=True, verbose_name='VF_VFI_full OS'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='vfi_os_part',
            field=models.PositiveIntegerField(blank=True, help_text='중심시야 대비감도 부분', null=True, verbose_name='VF_VFI_part OS'),
        ),
        migrations.AlterField(
            model_name='ird',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
