# Generated by Django 3.2.4 on 2022-05-06 03:17

from django.db import migrations, models
import ird.models


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0006_auto_20220421_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irdhistory',
            name='familyhistory_diagnosis1',
            field=ird.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '없음'), (1, '잘 모르겠음'), (2, '자녀 및 손자/손녀'), (3, '형제자매'), (4, '모계 직계(어머니, 외할아버지/할머니)'), (5, '부계 직계(아버지, 할아버지/할머니)'), (6, '모계 4촌 이내(외숙부/이모, 사촌 형제자매)'), (7, '부계 4촌 이내(백부/숙부/고모, 사촌 형제자매)')], max_length=200, null=True), blank=True, help_text='가족 중 같은 종류의 유전성 망막질환을 진단받은 사람이 있나요? 모두 선택해주세요', null=True, size=None, verbose_name='같은 종류 진단 받은 가족'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='familyhistory_diagnosis3',
            field=ird.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '없음'), (1, '잘 모르겠음'), (2, '자녀 및 손자/손녀'), (3, '형제자매'), (4, '모계 직계(어머니, 외할아버지/할머니)'), (5, '부계 직계(아버지, 할아버지/할머니)'), (6, '모계 4촌 이내(외숙부/이모, 사촌 형제자매)'), (7, '부계 4촌 이내(백부/숙부/고모, 사촌 형제자매)')], max_length=200, null=True), blank=True, help_text='가족 중 다른 종류의 유전성 망막질환을 진단받은 사람을 모두 선택해주세요', null=True, size=None, verbose_name='다른 종류 진단 받은 가족 선택'),
        ),
    ]
