# Generated by Django 3.1.8 on 2022-01-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0006_auto_20220105_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irdhistory',
            name='best_lp_lt',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='best_lp_rt',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='best_va',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='current_lp_lt',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='current_p_rt',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='current_va',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='familyhistory_diagnosis_name',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='first_lp_lt',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='first_lp_rt',
        ),
        migrations.RemoveField(
            model_name='irdhistory',
            name='first_va',
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='cataract_memo',
            field=models.TextField(blank=True, help_text='백내장이 있을 경우 추가 기록', null=True, verbose_name='백내장 관련 기록'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='color_sense_age',
            field=models.PositiveIntegerField(blank=True, help_text='몇 살 때, 색각을 처음 경험하셨나요?', null=True, verbose_name='색각 경험 나이'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='current_hospital',
            field=models.TextField(blank=True, help_text='현재 다니고 있는 병원', null=True),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='diagnosis_reason',
            field=models.TextField(blank=True, help_text='진단 받은 계기', null=True),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='eyeglasses_lens_memo',
            field=models.TextField(blank=True, help_text='안경이나 콘택트 렌즈를 사용할 경우 추가 기록', null=True, verbose_name='안경, 콘택트 렌즈 관련 기록'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='familyhistory_diagnosis1_name',
            field=models.CharField(blank=True, help_text='가족 중에서 같은 종류의 유전성 망막질환이 있는 경우 그분의 질병은 무엇인가요?', max_length=255, null=True, verbose_name='가족 같은 종류 진단 명'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='familyhistory_diagnosis2_name',
            field=models.CharField(blank=True, help_text='가족 중에서 다른 종류의 유전성 망막질환이 있는 경우 그분의 질병은 무엇인가요?', max_length=255, null=True, verbose_name='가족 다른 종류 진단 명'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='first_diagnosis_hospital',
            field=models.TextField(blank=True, help_text='첫 진단 병원', null=True),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='myodesopsia',
            field=models.IntegerField(blank=True, choices=[(1, '네'), (2, '아니오'), (3, '모름')], help_text='비문증이 있으신가요?', null=True, verbose_name='비문증'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='other_diagnosis_name',
            field=models.CharField(blank=True, help_text='그 외 다른 질환이 있는 경우 그 질병은 무엇인가요?', max_length=255, null=True, verbose_name='그외 다른 질환 명'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='other_hospital',
            field=models.TextField(blank=True, help_text='이 외에 내원했던 병원', null=True),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='register_date',
            field=models.DateField(blank=True, help_text='동의서 취득 날짜', null=True, verbose_name='동의서 취득 날짜'),
        ),
        migrations.AddField(
            model_name='irdhistory',
            name='subject_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Subject ID'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='best_va_lt',
            field=models.TextField(blank=True, null=True, verbose_name='가장 좋았을때 시력 좌'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='best_va_rt',
            field=models.TextField(blank=True, null=True, verbose_name='가장 좋았을때 시력 우'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='best_vfi_lt',
            field=models.TextField(blank=True, null=True, verbose_name='가장 좋았을때 시야 좌'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='best_vfi_rt',
            field=models.TextField(blank=True, null=True, verbose_name='가장 좋았을때 시야 우'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='current_vfi_lt',
            field=models.TextField(blank=True, null=True, verbose_name='현재 시야 좌'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='current_vfi_rt',
            field=models.TextField(blank=True, null=True, verbose_name='현재 시야 우'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='first_vfi_lt',
            field=models.TextField(blank=True, null=True, verbose_name='최초 진단시 시야 좌'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='first_vfi_rt',
            field=models.TextField(blank=True, null=True, verbose_name='최초 진단시 시야 우'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='job',
            field=models.TextField(blank=True, help_text='어떤 일을 하고 계신가요?', null=True, verbose_name='직업'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], help_text='성별', null=True, verbose_name='성별'),
        ),
    ]
