# Generated by Django 3.2.4 on 2022-06-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ird', '0007_auto_20220506_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irdhistory',
            name='cdva_od',
            field=models.CharField(blank=True, help_text='원거리교정시력', max_length=100, null=True, verbose_name='CDVA'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='cdva_os',
            field=models.CharField(blank=True, help_text='원거리교정시력', max_length=100, null=True, verbose_name='CDVA'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='cnva_od',
            field=models.CharField(blank=True, help_text='근거리교정시력', max_length=100, null=True, verbose_name='CNVA'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='cnva_os',
            field=models.CharField(blank=True, help_text='근거리교정시력', max_length=100, null=True, verbose_name='CNVA'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='udva_od',
            field=models.CharField(blank=True, help_text='원거리나안시력', max_length=100, null=True, verbose_name='UDVA'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='udva_os',
            field=models.CharField(blank=True, help_text='원거리나안시력', max_length=100, null=True, verbose_name='UDVA'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='unva_od',
            field=models.CharField(blank=True, help_text='근거리나안시력', max_length=100, null=True, verbose_name='UNVA'),
        ),
        migrations.AlterField(
            model_name='irdhistory',
            name='unva_os',
            field=models.CharField(blank=True, help_text='근거리나안시력', max_length=100, null=True, verbose_name='UNVA'),
        ),
    ]
