# Generated by Django 3.2.4 on 2021-07-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, unique=True)),
                ('case_no', models.IntegerField(blank=True, null=True)),
                ('family_no', models.IntegerField(blank=True, null=True)),
                ('family_hx', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'All')], null=True)),
                ('birth_date', models.DateField(auto_now=True)),
                ('date_at_dx', models.DateField(auto_now=True)),
                ('age_at_dx', models.IntegerField(blank=True, null=True)),
                ('date_at_evaluation', models.DateField(auto_now=True)),
                ('age_at_evaluation', models.IntegerField(blank=True, null=True)),
                ('dna', models.CharField(blank=True, max_length=200, unique=True)),
                ('protein', models.CharField(blank=True, max_length=200, unique=True)),
                ('domain', models.CharField(blank=True, max_length=20, unique=True)),
                ('mutation_type', models.IntegerField(blank=True, null=True)),
                ('inframe_deletion_or_insertion', models.IntegerField(blank=True, null=True)),
                ('nf1_haploinsufficiency_type', models.IntegerField(blank=True, null=True)),
                ('novel_mutation', models.BooleanField(default=False)),
                ('cafe_au_lait_spots', models.IntegerField(blank=True, null=True)),
                ('axillary_freckling', models.IntegerField(blank=True, null=True)),
                ('cutaneous_neurofibromas', models.IntegerField(blank=True, null=True)),
                ('wide_spread_diffuse_cutaneous_neurofibroma', models.IntegerField(blank=True, null=True)),
                ('relative_macrocephaly', models.IntegerField(blank=True, null=True)),
                ('lish_nodules', models.IntegerField(blank=True, null=True)),
                ('height_at_dx', models.FloatField(blank=True, null=True)),
                ('height_SDS', models.FloatField(blank=True, null=True)),
                ('learning_difficulty', models.IntegerField(blank=True, null=True)),
                ('adhd', models.IntegerField(blank=True, null=True)),
                ('autism', models.IntegerField(blank=True, null=True)),
                ('seizure', models.IntegerField(blank=True, null=True)),
                ('hypertension', models.IntegerField(blank=True, null=True)),
                ('cardiac_arrhthmia', models.IntegerField(blank=True, null=True)),
                ('cardiac_myopathy', models.IntegerField(blank=True, null=True)),
                ('_25_OH_vitamin_D', models.FloatField(blank=True, null=True)),
                ('HEARING', models.IntegerField(blank=True, null=True)),
                ('OTHER', models.IntegerField(blank=True, null=True)),
                ('BRAIN_MR_DATE', models.IntegerField(blank=True, null=True)),
                ('BRAIN_age_at_evaluation', models.IntegerField(blank=True, null=True)),
                ('BRAIN_FINDINGS', models.TextField(blank=True, null=True)),
                ('FASI', models.IntegerField(blank=True, null=True)),
                ('plexiform_neurofibromas', models.IntegerField(blank=True, null=True)),
                ('_3cm_above', models.IntegerField(blank=True, null=True)),
                ('disfigurement', models.IntegerField(blank=True, null=True)),
                ('aorta_bone_disruption_malignancy', models.IntegerField(blank=True, null=True)),
                ('malignancy', models.IntegerField(blank=True, null=True)),
                ('brain_tumor', models.IntegerField(blank=True, null=True)),
                ('nerve_root_tumor', models.IntegerField(blank=True, null=True)),
                ('malignant_peripheral_nerve_sheath_tumor', models.IntegerField(blank=True, null=True)),
                ('moyamoya_ds', models.IntegerField(blank=True, null=True)),
                ('osteopenia', models.IntegerField(blank=True, null=True)),
                ('dysplasia_of_long_bone', models.IntegerField(blank=True, null=True)),
                ('sphenoid_wing_dysplaisa', models.IntegerField(blank=True, null=True)),
                ('vertebral_dysplasia', models.IntegerField(blank=True, null=True)),
                ('dural_ectasia', models.IntegerField(blank=True, null=True)),
                ('scoliosis', models.IntegerField(blank=True, null=True)),
                ('breast_examination', models.IntegerField(blank=True, null=True)),
                ('operation', models.IntegerField(blank=True, null=True)),
                ('last_follow_up_date', models.IntegerField(blank=True, null=True)),
                ('last_follow_up_age', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
