# Generated by Django 3.2.4 on 2021-07-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf',
            name='_3cm_above',
        ),
        migrations.AddField(
            model_name='crf',
            name='FASI_FINDINGS',
            field=models.TextField(blank=True, help_text='FASI  발견 부위 (영상학적 판단)', null=True, verbose_name='FASI FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='optic_pathway_glioma',
            field=models.IntegerField(blank=True, help_text='시신경교종 (유무; 안과적 진단)', null=True, verbose_name='Optic pathway glioma'),
        ),
        migrations.AddField(
            model_name='crf',
            name='plexiform_neurofibromas_3cm_above',
            field=models.IntegerField(blank=True, help_text='총상신경섬유종 (3cm 이상; 임상학적 진단)', null=True, verbose_name='Plexiform neurofibromas(>=3cm)'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='BRAIN_FINDINGS',
            field=models.TextField(blank=True, help_text='뇌 MR 스캔 결과 기술 (영상학적 판단)', null=True, verbose_name='MR FINDINGS'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='BRAIN_MR_DATE',
            field=models.DateField(blank=True, help_text='뇌 MR 촬영 날짜', null=True, verbose_name='BRAIN MR DATE'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='BRAIN_age_at_evaluation',
            field=models.IntegerField(blank=True, help_text='뇌 MR 촬영시 연령', null=True, verbose_name='Age at brain MR'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='FASI',
            field=models.IntegerField(blank=True, help_text='고음영 병변 (유무; unidentified bright objects, UBO; 임상적 판단)', null=True, verbose_name='FASI(focal areas of signal intensity)'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='HEARING',
            field=models.IntegerField(blank=True, help_text='청력 장애 (유무; 신경학적 판단)', null=True, verbose_name='Hearing difficulty'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='OTHER',
            field=models.IntegerField(blank=True, help_text='기타', null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='_25_OH_vitamin_D',
            field=models.FloatField(blank=True, help_text='25-하이드록시 비타민 D 검사 수치', null=True, verbose_name='25-OH vitamin D'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='adhd',
            field=models.IntegerField(blank=True, help_text='주의력결핍 과잉행동장애 (심리학적 평가)', null=True, verbose_name='ADHD'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='age_at_dx',
            field=models.IntegerField(blank=True, help_text='진단시 연령', null=True, verbose_name='Age at Dx'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='age_at_evaluation',
            field=models.IntegerField(blank=True, help_text='유전자 검사시 연령', null=True, verbose_name='Age at evaluation'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='autism',
            field=models.IntegerField(blank=True, help_text='자폐증 (임상학적 평가)', null=True, verbose_name='Autism'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='axillary_freckling',
            field=models.IntegerField(blank=True, help_text='겨드랑이 부위 주근깨 (임상학적 진단)', null=True, verbose_name='Axillary Freckling'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='birth_date',
            field=models.DateField(auto_now=True, help_text='생년월일', verbose_name='Birth year and month'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='cafe_au_lait_spots',
            field=models.IntegerField(blank=True, help_text='커피색의 반점', null=True, verbose_name='Café au lait spots [ >6 and >(0.5 cm or 1.5 cm)]'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='cardiac_arrhthmia',
            field=models.IntegerField(blank=True, help_text='심장 부정맥 (유무; 임상학적 평가)', null=True, verbose_name='Cardiac arrhythmia'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='cardiac_myopathy',
            field=models.IntegerField(blank=True, help_text='심장 근병증 (유무; 영상학적 소견)', null=True, verbose_name='Cardiac myopathy'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='case_no',
            field=models.IntegerField(blank=True, help_text='사건/차트 번호', null=True, verbose_name='Case no.'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='cutaneous_neurofibromas',
            field=models.IntegerField(blank=True, help_text='피부신경섬유종 (피부표면에 나타나는 종양; 임상학적 진단)', null=True, verbose_name='Cutaneous neurofibromas'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='date_at_dx',
            field=models.DateField(auto_now=True, help_text='진단 받은 날짜', verbose_name='Date at Dx'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='date_at_evaluation',
            field=models.DateField(auto_now=True, help_text='유전자 검사 날짜', verbose_name='Date at evaluation'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='dna',
            field=models.CharField(blank=True, help_text='유전자 변이 (DNA)', max_length=200, unique=True, verbose_name='DNA'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='domain',
            field=models.CharField(blank=True, help_text='유전자 도메인', max_length=20, unique=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='family_hx',
            field=models.IntegerField(blank=True, help_text='가족 병력', null=True, verbose_name='Family Hx'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='family_no',
            field=models.IntegerField(blank=True, help_text='가족 번호', null=True, verbose_name='Family no.'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='height_SDS',
            field=models.FloatField(blank=True, help_text='상대적 키 (신체적 평가, SD score)', null=True, verbose_name='Height (SDS)'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='height_at_dx',
            field=models.FloatField(blank=True, help_text='진단시 환자의 키 (신체적 평가)', null=True, verbose_name='Height at Dx'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='hypertension',
            field=models.IntegerField(blank=True, help_text='고혈압 (유무; 임상학적 평가)', null=True, verbose_name='Hypertension'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='inframe_deletion_or_insertion',
            field=models.IntegerField(blank=True, help_text='인델 돌연변이(유무; 유전자 인프레임 삭제 또는 삽입; 유전자 전사와 번역 과정이 중지되지 않음)', null=True, verbose_name='Inframe deletion or insertion'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='learning_difficulty',
            field=models.IntegerField(blank=True, help_text='학습장애 (심리학적 평가)', null=True, verbose_name='Learning difficulty'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='lish_nodules',
            field=models.IntegerField(blank=True, help_text='홍채에 작고 색조를 띈 과오종인 리쉬결절 (안과적 평가)', null=True, verbose_name='Lish nodules'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='mutation_type',
            field=models.IntegerField(blank=True, help_text='돌연변이 종류<br/>1:missense<br/>2:nonsense<br/>3:frameshift<br/>4:splicing<br/>5:large deletion', null=True, verbose_name='Mutation type'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='name',
            field=models.CharField(blank=True, help_text='환자 이름', max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='nf1_haploinsufficiency_type',
            field=models.IntegerField(blank=True, help_text='반수체 부족 유형', null=True, verbose_name='NF1 haploinsufficiency type'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='novel_mutation',
            field=models.BooleanField(default=False, help_text='드 노보 유전자 돌연변이 (유무; 유전성이 아닌 돌연변이)', verbose_name='Novel mutation'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='patient_number',
            field=models.IntegerField(blank=True, help_text='환자 번호', null=True, verbose_name='Patient number'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='plexiform_neurofibromas',
            field=models.IntegerField(blank=True, help_text='총상신경섬유종 (유무; 임상학적 진단)', null=True, verbose_name='Plexiform neurofibromas'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='protein',
            field=models.CharField(blank=True, help_text='유전자 변이 (protein)', max_length=200, unique=True, verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='relative_macrocephaly',
            field=models.IntegerField(blank=True, help_text='상대적 대두증 (성조숙증으로 인한 평균 이상의 머리둘레; 신체적 평가)', null=True, verbose_name='Relative macrocephaly'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='seizure',
            field=models.IntegerField(blank=True, help_text='발작 (유무; 임상학적 평가)', null=True, verbose_name='Seizure'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'All')], help_text='성별', null=True, verbose_name='SEX'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='wide_spread_diffuse_cutaneous_neurofibroma',
            field=models.IntegerField(blank=True, help_text='피하신경섬유종 (진피와 지방층 사이에 나타나는 종양; 임상학적 진단)', null=True, verbose_name='Wide spread diffuse cutaneous neurofibroma'),
        ),
    ]
