# Generated by Django 3.2.4 on 2021-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf',
            name='fasi',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], help_text='고음영 병변 (unidentified bright objects, UBO; 임상적 판단)<br/>0 : 없음<br/>1 : 있음<br/>2 : 모름', null=True, verbose_name='FASI (focal areas of signal intensity)'),
        ),
    ]
