# Generated by Django 3.2.4 on 2021-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='자동 반영', null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='birth_date',
            field=models.DateField(blank=True, help_text='생년월일<br/>입력시 오늘 날짜 기준으로 나이가 입력됩니다.', null=True, verbose_name='Birth year and month'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='family_hx',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, '모름')], help_text='가족 병력<br/>(0:없음, 1: 있음, 모름)', null=True, verbose_name='Family Hx'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='sex',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'All')], help_text='성별<br/>(0:남자, 1: 여자, 3:전부, 모름)', null=True, verbose_name='SEX'),
        ),
    ]
