# Generated by Django 3.2.4 on 2021-09-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0002_alter_crf_fasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crfoperations',
            options={'verbose_name': 'Operations', 'verbose_name_plural': 'Operations'},
        ),
    ]
