# Generated by Django 3.2.4 on 2021-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0002_auto_20210727_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf',
            name='Age_at_Spine_MR',
            field=models.IntegerField(blank=True, help_text='척추 MR 촬영시 연령', null=True, verbose_name='Age at Spine MR'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Age_at_Spine_MR_FINDINGS',
            field=models.TextField(blank=True, help_text='척추 MR 스캔 결과 기술 (영상학적 판단)', null=True, verbose_name='Age at Spine MR FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Age_at_Whole_body_MR',
            field=models.TextField(blank=True, help_text='전신 MR 촬영시 나이', null=True, verbose_name='Age at Whole body MR'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Age_at_Whole_body_MR_FINDINGS',
            field=models.TextField(blank=True, help_text='전신 MR 촬영 결과 기술 (영상학적 판단)', null=True, verbose_name='Age at Whole body MR FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Age_at_brain_MR_FINDINGS',
            field=models.IntegerField(blank=True, help_text='부정맥 치료에 사용된 의료 시술/기술', null=True, verbose_name='Age at brain MR FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='BIRADS_I_II_III_IV',
            field=models.CharField(blank=True, help_text='질환 경과 단계', max_length=200, null=True, verbose_name='BIRADS I/II/III/IV'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Breast_USG_FINDINGS',
            field=models.TextField(blank=True, help_text='유방 검사 결과 기술 (외과학적/영상학적 판단)', null=True, verbose_name='Breast USG FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Cardiac_myopathy_FINDINGS',
            field=models.TextField(blank=True, help_text='이상 소견', null=True, verbose_name='Cardiac myopathy FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Clinical_FINDINGS',
            field=models.TextField(blank=True, help_text='임상 소견', null=True, verbose_name='Clinical FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Femur_z_score',
            field=models.IntegerField(blank=True, help_text='대퇴골 (통계학적 수치)', null=True, verbose_name='Femur (z score)'),
        ),
        migrations.AddField(
            model_name='crf',
            name='NF1_genotype',
            field=models.CharField(blank=True, help_text='연관 유전자 자위', max_length=200, unique=True, verbose_name='NF1 genotype'),
        ),
        migrations.AddField(
            model_name='crf',
            name='SPINE_MR_DATE',
            field=models.DateField(auto_now=True, help_text='척추 MR 스캔 촬영 날짜', verbose_name='SPINE MR DATE'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Spine_z_score',
            field=models.IntegerField(blank=True, help_text='척추 (통계학적 수치)', null=True, verbose_name='Spine (z score)'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Vascular_anomaly',
            field=models.IntegerField(blank=True, help_text='혈관 이상 (유무; 영상학적/흉부외과적 진단)', null=True, verbose_name='Vascular anomaly'),
        ),
        migrations.AddField(
            model_name='crf',
            name='Whole_body_MR_DATE',
            field=models.DateField(auto_now=True, help_text='전신 MR 촬영 날짜', verbose_name='Whole body MR DATE'),
        ),
        migrations.AddField(
            model_name='crf',
            name='age_at_breast_USG',
            field=models.IntegerField(blank=True, help_text='유방 초음파 검사시 연령', null=True, verbose_name='Age at breast USG'),
        ),
        migrations.AddField(
            model_name='crf',
            name='biopsy',
            field=models.IntegerField(blank=True, help_text='조직검사 (유무)', null=True, verbose_name='biopsy'),
        ),
        migrations.AddField(
            model_name='crf',
            name='biopsy_FINDINGS',
            field=models.TextField(blank=True, help_text='조직검사 결과', null=True, verbose_name='biopsy FINDINGS'),
        ),
        migrations.AddField(
            model_name='crf',
            name='dysplasia_of_long_bone_location',
            field=models.CharField(blank=True, help_text='관찰 부위', max_length=200, null=True, verbose_name='Dysplasia of long bone location'),
        ),
        migrations.AddField(
            model_name='crf',
            name='with_pain',
            field=models.IntegerField(blank=True, help_text='통증 동반 (유무)', null=True, verbose_name='통증 동반'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='aorta_bone_disruption_malignancy',
            field=models.IntegerField(blank=True, help_text='위험한 부위의 이형성증', null=True, verbose_name='위험한 부위(aorta, bone disruption, malignancy) 침범 여부'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='brain_tumor',
            field=models.IntegerField(blank=True, help_text='뇌종양 (유무)', null=True, verbose_name='Brain tumor'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='breast_examination',
            field=models.IntegerField(blank=True, help_text='유방 초음파 검사 (유무)', null=True, verbose_name='Breast examination'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='disfigurement',
            field=models.IntegerField(blank=True, help_text='이형성증', null=True, verbose_name='Disfigurement'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='dural_ectasia',
            field=models.IntegerField(blank=True, help_text='경막 확장증 (유무)', null=True, verbose_name='Dural ectasia'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='dysplasia_of_long_bone',
            field=models.IntegerField(blank=True, help_text='경골의 이형성증', null=True, verbose_name='Dysplasia of long bone'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='last_follow_up_age',
            field=models.FloatField(blank=True, help_text='최근 재진/팔로업시 연령', null=True, verbose_name='last f/u age'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='last_follow_up_date',
            field=models.IntegerField(blank=True, help_text='최근 재진/팔로업 날짜', null=True, verbose_name='last f/u date'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='malignancy',
            field=models.IntegerField(blank=True, help_text='악성 종양 (유무)', null=True, verbose_name='Malignancy'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='malignant_peripheral_nerve_sheath_tumor',
            field=models.IntegerField(blank=True, help_text='악성 말초신경 수초 종양 (유무)', null=True, verbose_name='Malignant peripheral nerve sheath tumor'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='moyamoya_ds',
            field=models.IntegerField(blank=True, help_text='모야모야 진단 (합병증 유무)', null=True, verbose_name='Moyamoya disease'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='nerve_root_tumor',
            field=models.IntegerField(blank=True, help_text='신경근 종양 (유무)', null=True, verbose_name='Nerve root tumor'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='operation',
            field=models.IntegerField(blank=True, help_text='수술 유무 (유무)', null=True, verbose_name='OPERATION'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='osteopenia',
            field=models.IntegerField(blank=True, help_text='골감소증 (유무; 정형외과적 판단)', null=True, verbose_name='Osteopenia'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='scoliosis',
            field=models.IntegerField(blank=True, help_text='척추측만증 (유무; 신체적 평가)', null=True, verbose_name='Scoliosis'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='sphenoid_wing_dysplaisa',
            field=models.IntegerField(blank=True, help_text='접형골의 비정상적인 발달 및 형성부전', null=True, verbose_name='Sphenoid wing dysplaisa'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='vertebral_dysplasia',
            field=models.IntegerField(blank=True, help_text='척추 이형서증 (유무; 신체적 평가)', null=True, verbose_name='Vertebral dysplasia'),
        ),
    ]
