# Generated by Django 3.2.4 on 2021-07-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0003_auto_20210727_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrfOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, help_text='수술 번호', null=True, verbose_name='수술번호')),
                ('date', models.DateField(blank=True, help_text='수술 시기', null=True, verbose_name='수술 시기')),
                ('age', models.IntegerField(blank=True, help_text='수술 나이', null=True, verbose_name='수술 나이')),
                ('status', models.CharField(blank=True, help_text='수술 부위', max_length=200, null=True, verbose_name='수술 부위')),
                ('reason', models.TextField(blank=True, help_text='수술 이유', null=True, verbose_name='수술 이유')),
                ('method', models.CharField(blank=True, help_text='완전절제/부분절제', max_length=200, null=True, verbose_name='완전절제/부분절제')),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crfOperations', to='nf1.crf')),
            ],
        ),
    ]
