# Generated by Django 3.2.4 on 2021-12-10 03:08

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0003_alter_crfoperations_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf',
            name='birth_year_and_month',
        ),
        migrations.AlterField(
            model_name='crf',
            name='name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='환자 이름', max_length=200, null=True, verbose_name='Name'),
        ),
    ]
