# Generated by Django 3.2.4 on 2021-12-10 03:09

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0004_auto_20211210_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf',
            name='birth_year_and_month',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, help_text='생년월일<br/>입력시 오늘 날짜 기준으로 나이가 입력됩니다.', null=True, verbose_name='Birth year and month'),
        ),
    ]
