# Generated by Django 3.1.8 on 2022-01-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0005_crf_birth_year_and_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf',
            name='date_at_evaluation_diagnosis',
        ),
        migrations.AlterField(
            model_name='crf',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crfoperations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
