# Generated by Django 3.2.4 on 2022-03-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0006_auto_20220121_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf',
            name='age_at_brain_mr_findings',
        ),
        migrations.RemoveField(
            model_name='crf',
            name='case_no',
        ),
        migrations.RemoveField(
            model_name='crf',
            name='family_no',
        ),
        migrations.RemoveField(
            model_name='crf',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crf',
            name='osteopenia',
        ),
        migrations.AddField(
            model_name='crf',
            name='arrhythmia_treatment',
            field=models.TextField(blank=True, help_text='부정맥 치료에 사용된 의료 시술/기술', null=True, verbose_name='Arrhythmia treatment'),
        ),
        migrations.AddField(
            model_name='crf',
            name='bmd',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], help_text='골밀도<br/>0 : 미시행<br/>1 : 시행', null=True, verbose_name='BMD 시행여부'),
        ),
        migrations.AddField(
            model_name='crf',
            name='bmd_1',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], help_text='골밀도(정형외과적 판단)<br/>0 : 정상<br/>1 : 골감소증<br/>2 : 골다공증', null=True, verbose_name='BMD'),
        ),
        migrations.AddField(
            model_name='crf',
            name='brain_mr',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], help_text='Brain MR 시행 여부<br/>0 : 미시행<br/>1 : 시행', null=True, verbose_name='Brain MR 시행 여부'),
        ),
        migrations.AddField(
            model_name='crf',
            name='familyhistory_diagnosis',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='0: 부<br/>1: 모<br/>2: 형제<br/>3: 자녀', null=True, verbose_name='familyhistory_diagnosis'),
        ),
        migrations.AddField(
            model_name='crf',
            name='oh_25_vitamin_d_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='25-하이드록시 비타민 D 검사 수치<br/>단위 ng/mL', max_digits=10, null=True, verbose_name='25-OH vitamin D'),
        ),
        migrations.AddField(
            model_name='crf',
            name='spine_mr',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], help_text='척추 MR 시행 여부<br/>0 : 미시행<br/>1 : 시행', null=True, verbose_name='Spine MR 시행여부'),
        ),
        migrations.AddField(
            model_name='crf',
            name='whole_body_mr',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], help_text='Whole body MR 시행 여부<br/>0 : 미시행<br/>1 : 시행', null=True, verbose_name='Whole body MR'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='breast_examination',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], help_text='유방 초음파 검사<br/>0 : 미시행<br/>1 : 시행', null=True, verbose_name='Breast examination'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crf',
            name='oh_25_vitamin_d',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], help_text='25-하이드록시 비타민 D 검사 시행 여부<br/>0 : 미시행<br/>1 : 시행', null=True, verbose_name='25-OH vitamin D 시행여부'),
        ),
        migrations.AlterField(
            model_name='crfoperations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
