# Generated by Django 3.2.4 on 2022-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0007_auto_20220328_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf',
            name='biopsy',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], help_text='조직검사 <br/>0 : 미시행<br/>1 : 시행', null=True, verbose_name='Biopsy'),
        ),
    ]
