# Generated by Django 3.2.4 on 2022-07-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0008_alter_crf_biopsy'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf',
            name='icf_date',
            field=models.DateField(blank=True, help_text='연구 동의서 취득일', null=True, verbose_name='ICF date'),
        ),
    ]
