# Generated by Django 3.2.4 on 2022-07-20 06:49

from django.db import migrations, models
import nf1.models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0009_crf_icf_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf',
            name='familyhistory_diagnosis_multiple',
            field=nf1.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(0, '부'), (1, '모'), (2, '형제'), (3, '자녀')], max_length=200, null=True), blank=True, help_text='0: 부<br/>1: 모<br/>2: 형제<br/>3: 자녀', null=True, size=None, verbose_name='familyhistory_diagnosis'),
        ),
    ]
