# Generated by Django 3.2.4 on 2022-07-21 05:41

from django.db import migrations, models
import nf1.models


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0010_crf_familyhistory_diagnosis_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf',
            name='familyhistory_diagnosis_multiple',
            field=nf1.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[(-1, '-'), (0, '부'), (1, '모'), (2, '형제'), (3, '자녀')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='familyhistory_diagnosis'),
        ),
    ]
