# Generated by Django 3.2.4 on 2022-07-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf1', '0011_alter_crf_familyhistory_diagnosis_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf',
            name='familyhistory_diagnosis',
        ),
    ]
