from django.db import models


class Ird(models.Model):
    SEX_TYPE = ((1, 'Male'), (2, 'Female'), (3, 'All'))
    SORTATION_TYPE = ((1,1), (2,2))

    case_no = models.PositiveIntegerField('차트번호', null=True, blank=True)
    name = models.CharField('성명', max_length=20, blank=True)
    birth_year_and_month = models.DateTimeField('생년월일', blank=True)
    sex = models.PositiveIntegerField('SEX', choices=SEX_TYPE, null=True, blank=True)
    finding = models.TextField('특이사항', blank=True)
    sortation = models.PositiveIntegerField('구분', choices=SORTATION_TYPE, null=True, blank=True)
    ARK_SPH = models.PositiveIntegerField('ARK_SPH', null=True, blank=True)
    ARK_CYL = models.PositiveIntegerField('ARK_CYL', null=True, blank=True)
    ARK_AXIS = models.PositiveIntegerField('ARK_AXIS', null=True, blank=True)
    ARK_K1 = models.PositiveIntegerField('ARK_K1', null=True, blank=True)
    ARK_K2 = models.PositiveIntegerField('ARK_K2', null=True, blank=True)
    ARK_KM = models.PositiveIntegerField('ARK_KM', null=True, blank=True)
    ARK_K_cyl = models.PositiveIntegerField('ARK_K(cyl)', null=True, blank=True)
    ARK_K_Axis = models.PositiveIntegerField('ARK_K(Axis)', null=True, blank=True)
    UDVA = models.PositiveIntegerField('UDVA', null=True, blank=True)
    UNVA = models.PositiveIntegerField('UNVA', null=True, blank=True)
    CDVA = models.PositiveIntegerField('CDVA', null=True, blank=True)
    CNVA = models.PositiveIntegerField('CNVA', null=True, blank=True)
    IOP = models.PositiveIntegerField('IOP', null=True, blank=True)
    OCT_CST = models.PositiveIntegerField('OCT_CST', null=True, blank=True)
    Cones_a = models.PositiveIntegerField('Cones_a', null=True, blank=True)
    Cones_b = models.PositiveIntegerField('Cones_b', null=True, blank=True)
    Flicker = models.PositiveIntegerField('Flicker', null=True, blank=True)
    Pattern_N35_mono = models.PositiveIntegerField('Pattern_N35(단안)', null=True, blank=True)
    Pattern_P50_mono = models.PositiveIntegerField('Pattern_P50(단안)', null=True, blank=True)
    Pattern_N95_mono = models.PositiveIntegerField('Pattern_N95(단안)', null=True, blank=True)
    Pattern_N35_bi = models.PositiveIntegerField('Pattern_N35(양안)', null=True, blank=True)
    Pattern_P50_bi = models.PositiveIntegerField('Pattern_P50(양안)', null=True, blank=True)
    Pattern_N95_bi = models.PositiveIntegerField('Pattern_N95(양안)', null=True, blank=True)
    Rods_a = models.PositiveIntegerField('Rods_a', null=True, blank=True)
    Rods_b = models.PositiveIntegerField('Rods_b', null=True, blank=True)
    Maximal_a = models.PositiveIntegerField('Maximal_a', null=True, blank=True)
    Maximal_b = models.PositiveIntegerField('Maximal_b', null=True, blank=True)
    Maximal_c = models.PositiveIntegerField('Maximal_c', null=True, blank=True)
    VEP_N75 = models.PositiveIntegerField('VEP_N75', null=True, blank=True)
    VEP_P100 = models.PositiveIntegerField('VEP_P100', null=True, blank=True)
    VEP_N145 = models.PositiveIntegerField('VEP_N145', null=True, blank=True)
    VEP_P1 = models.PositiveIntegerField('VEP_P1', null=True, blank=True)
    VEP_P2 = models.PositiveIntegerField('VEP_P2', null=True, blank=True)

