from django.db import models


class Ird(models.Model):
    SEX_TYPE = ((1, 'Male'), (2, 'Female'), (3, 'All'))
    SORTATION_TYPE = ((1,1), (2,2))

    case_no = models.PositiveIntegerField('차트번호', null=True, blank=True)
    name = models.CharField('성명', max_length=20, blank=True)
    birth_year_and_month = models.DateTimeField('생년월일', blank=True)
    sex = models.PositiveIntegerField('SEX', choices=SEX_TYPE, null=True, blank=True)
    finding = models.TextField('특이사항', blank=True)
    sortation = models.PositiveIntegerField('구분', choices=SORTATION_TYPE, null=True, blank=True)
    # models.DecimalField('Height at Dx', max_digits=10, decimal_places=2, null=True, blank=True, help_text='진단시 환자의 키 (신체적 평가)')
    ARK_SPH = models.DecimalField('ARK_SPH', max_digits=10, decimal_places=2, null=True, blank=True)
    ARK_CYL = models.DecimalField('ARK_CYL', max_digits=10, decimal_places=2, null=True, blank=True)
    ARK_AXIS = models.DecimalField('ARK_AXIS', max_digits=10, decimal_places=2, null=True, blank=True)
    ARK_K1 = models.DecimalField('ARK_K1', max_digits=10, decimal_places=2, null=True, blank=True)
    ARK_K2 = models.DecimalField('ARK_K2', max_digits=10, decimal_places=2, null=True, blank=True)
    ARK_KM = models.DecimalField('ARK_KM', max_digits=10, decimal_places=2, null=True, blank=True)
    ARK_K_cyl = models.DecimalField('ARK_K(cyl)', max_digits=10, decimal_places=2, null=True, blank=True)
    ARK_K_Axis = models.DecimalField('ARK_K(Axis)', max_digits=10, decimal_places=2, null=True, blank=True)
    UDVA = models.DecimalField('UDVA', max_digits=10, decimal_places=2, null=True, blank=True)
    UNVA = models.DecimalField('UNVA', max_digits=10, decimal_places=2, null=True, blank=True)
    CDVA = models.DecimalField('CDVA', max_digits=10, decimal_places=2, null=True, blank=True)
    CNVA = models.DecimalField('CNVA', max_digits=10, decimal_places=2, null=True, blank=True)
    IOP = models.DecimalField('IOP', max_digits=10, decimal_places=2, null=True, blank=True)
    OCT_CST = models.DecimalField('OCT_CST', max_digits=10, decimal_places=2, null=True, blank=True)
    Cones_a = models.DecimalField('Cones_a', max_digits=10, decimal_places=2, null=True, blank=True)
    Cones_b = models.DecimalField('Cones_b', max_digits=10, decimal_places=2, null=True, blank=True)
    Flicker = models.DecimalField('Flicker', max_digits=10, decimal_places=2, null=True, blank=True)
    Pattern_N35_mono = models.DecimalField('Pattern_N35(단안)', max_digits=10, decimal_places=2, null=True, blank=True)
    Pattern_P50_mono = models.DecimalField('Pattern_P50(단안)', max_digits=10, decimal_places=2, null=True, blank=True)
    Pattern_N95_mono = models.DecimalField('Pattern_N95(단안)', max_digits=10, decimal_places=2, null=True, blank=True)
    Pattern_N35_bi = models.DecimalField('Pattern_N35(양안)', max_digits=10, decimal_places=2, null=True, blank=True)
    Pattern_P50_bi = models.DecimalField('Pattern_P50(양안)', max_digits=10, decimal_places=2, null=True, blank=True)
    Pattern_N95_bi = models.DecimalField('Pattern_N95(양안)', max_digits=10, decimal_places=2, null=True, blank=True)
    Rods_a = models.DecimalField('Rods_a', max_digits=10, decimal_places=2, null=True, blank=True)
    Rods_b = models.DecimalField('Rods_b', max_digits=10, decimal_places=2, null=True, blank=True)
    Maximal_a = models.DecimalField('Maximal_a', max_digits=10, decimal_places=2, null=True, blank=True)
    Maximal_b = models.DecimalField('Maximal_b', max_digits=10, decimal_places=2, null=True, blank=True)
    Maximal_c = models.DecimalField('Maximal_c', max_digits=10, decimal_places=2, null=True, blank=True)
    VEP_N75 = models.DecimalField('VEP_N75', max_digits=10, decimal_places=2, null=True, blank=True)
    VEP_P100 = models.DecimalField('VEP_P100', max_digits=10, decimal_places=2, null=True, blank=True)
    VEP_N145 = models.DecimalField('VEP_N145', max_digits=10, decimal_places=2, null=True, blank=True)
    VEP_P1 = models.DecimalField('VEP_P1', max_digits=10, decimal_places=2, null=True, blank=True)
    VEP_P2 = models.DecimalField('VEP_P2', max_digits=10, decimal_places=2, null=True, blank=True)

